# Generated by Django 6.0.4 on 2026-05-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tag',
            field=models.ManyToManyField(blank=True, to='tag.tag'),
        ),
    ]
