# Generated by Django 6.0.4 on 2026-04-26 17:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='categorie',
            name='nom',
            field=models.CharField(default='categorie', max_length=50),
        ),
        migrations.AddField(
            model_name='media',
            name='date_upload',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='media',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='note.note'),
        ),
        migrations.AddField(
            model_name='media',
            name='type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='media',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='note',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='note.categorie'),
        ),
        migrations.AddField(
            model_name='note',
            name='contenu',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='note',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='note',
            name='titre',
            field=models.CharField(default='sans titre', max_length=50),
        ),
        migrations.AddField(
            model_name='partage',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partages', to='note.note'),
        ),
        migrations.AddField(
            model_name='partage',
            name='permission',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='version',
            name='contenu',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='version',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='version',
            name='note',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='note.note'),
            preserve_default=False,
        ),
    ]
