# Generated by Django 6.0.4 on 2026-05-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_partage_collaborateur_partage_date_partage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medias/images/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('lien', 'Lien'), ('image', 'Image')], default='lien', max_length=50),
        ),
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
