# Generated by Django 6.0.4 on 2026-04-26 17:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_categorie_description_categorie_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='note.note'),
        ),
        migrations.AlterField(
            model_name='partage',
            name='note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partages', to='note.note'),
        ),
    ]
