# Generated by Django 6.0.4 on 2026-04-26 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_alter_media_note_alter_partage_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='note.note'),
        ),
        migrations.AlterField(
            model_name='partage',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partages', to='note.note'),
        ),
    ]
