# Generated by Django 6.0.4 on 2026-05-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_note_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='est_interne',
            field=models.BooleanField(default=False),
        ),
    ]
