# Generated by Django 6.0.4 on 2026-05-09 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_note_tag'),
        ('note', '0005_media_est_interne'),
    ]

    operations = [
    ]
