# Generated by Django 6.0.4 on 2026-05-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_merge_0002_note_tag_0005_media_est_interne'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='tag',
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='notes', through='tag.note_tag', to='tag.tag'),
        ),
    ]
