<<<<<<< HEAD
# Generated by Django 6.0.4 on 2026-04-28 12:56
=======
# Generated by Django 6.0.4 on 2026-04-28 14:26
>>>>>>> 1d81b0ba55d579daae2d2dc642b14248b34d9821

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id_notification', models.AutoField(primary_key=True, serialize=False)),
                ('messsage', models.CharField(blank=True, default='', max_length=255)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('lu', models.BooleanField(default=False)),
            ],
        ),
    ]
