<<<<<<< HEAD
# Generated by Django 6.0.4 on 2026-04-28 12:56
=======
# Generated by Django 6.0.4 on 2026-04-28 14:26
>>>>>>> 1d81b0ba55d579daae2d2dc642b14248b34d9821

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notification', '0001_initial'),
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='utilisateur.utilisateur'),
        ),
    ]
