# Generated by Django 6.0.4 on 2026-04-28 12:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id_contenu', models.BigAutoField(primary_key=True, serialize=False)),
                ('contenu_com', models.TextField(blank=True, default='')),
                ('date_com', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='utilisateur.utilisateur')),
            ],
        ),
    ]
