# Generated by Django 6.0.4 on 2026-04-28 12:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id_contenu', models.BigAutoField(primary_key=True, serialize=False)),
                ('contenu_com', models.TextField(blank=True, default='')),
                ('date_com', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
