# Generated by Django 6.0.4 on 2026-05-08 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentaire', '0002_initial'),
        ('note', '0002_note_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='note.note'),
        ),
    ]
