# Generated by Django 6.0.4 on 2026-04-28 12:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('note', '0004_alter_media_note_alter_partage_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id_tag', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_tag', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='note_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='note.note')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tag.tag')),
            ],
            options={
                'unique_together': {('note', 'tag')},
            },
        ),
    ]
