# Generated by Django 6.0.4 on 2026-04-21 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='date_uploadie',
            new_name='date_uploade',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='date_pref',
            new_name='date_notif',
        ),
        migrations.RenameField(
            model_name='version',
            old_name='date',
            new_name='date_modification_v',
        ),
    ]
